### ISSUE TITLE
Not Enough Wands

### ISSUE THREAD

**Issue by Iceciro** [SoSly/minecraft#23]
**Mod URL:** https://www.curseforge.com/minecraft/mc-mods/not-enough-wands

**Mod Description:** This is a mod that adds various utility wands to Minecraft. The main strength of this mod is the configurability. 

**Why you want it:** I'm primarily interested in the Builders, Displacement, and Swapping wands. These make building in Minecraft a lot easier. They can be configured to have limited durability, or cost XP. The other wands can be disabled in the config.

**Comment by nivthefox** [comment]
My concerns with this mod, one wand at a time:

**Swapping Wand:** This is probably fine, as long as it requires you to have the blocks you're swapping to in your inventory.

**Teleportation Wand:** So many of our magic mods have ways to do this. it's one of the benefits of the magics.  This wand takes a little away from those mods.

**Capturing Wand:** I have always hated this kind of thing (we previously had it in nets). Between purchasing mobs at the trader, and carryon, this functionality is already as good as I want it to be.

**Building Wand:** I need to know more about this, but it's probably okayish.

**Illumination Wand:** This absolutely takes away from our magic mods. One of the coolest parts of the magic mods is reaching the point where you don't need torches anymore.  I hate this wand.

**Moving Wand:** This is literally just carryon.

**Displacement Wand:** This is possibly okay, but I have concerns about what you can do with it while caving or in the nether.

**Protection Wand:** We don't really need this since kabooms have already been severely nerfed.

**Master Protection Wand:** Why ... does this even exist.  "We made a wand to stop griefing! Then we made another wand that can override that other wand!"  This is stupid.

**Acceleration Wand:** Bonemeal for all?  Bonemeal for Furnaces?  Eh.

I might be okay with enabling some of those using XP as the fuel.  I'm hesitant, though.

**Comment by Iceciro** [comment]
The Displacement, Swapping, and Builder's wands are the main ones I want. A lot of the other ones might introduce the problems above, and I'm in favor of disabling them.

The Master Protection Wand is generally set as an admin tool, by the by.

Swapping does require the blocks to be in your inventory (and for you to have space for the swapped blocks, by the by.)

**Comment by InterwovenWasTaken** [comment]
Astral Sorcery has wands for several of these. I would rather have some way to be able to give people Formation Wands and Conversion Wands, or have the expansion of features be part of a more general push. _Especially_ for Wizardry, because it has massively more flexible combat and self-buff options already.

The Acceleration Wand I would be especially disappointed to see; one of Astral Sorcery's most rare and difficult to arrange rituals is for universal machine acceleration, and I've been building up to it for a little while now. And the most fundamental spell of Roots is being able to semi-freely force-accelerate plant growth.

I've invested myself heavily into Astral Sorcery in part for the utility wands and rituals it offers; I would rather not have a mod introduced to bypass it.

**Comment by nivthefox** [comment]
Can you explain how the Formation and Conversion wands work?

**Comment by InterwovenWasTaken** [comment]
All Astral Sorcery utility wands (Formation, Conversion, Impulsion, and Illumination) use a shared 'charge' system with a variable recharge rate based on the chunk's natural starlight, the time of day, etc.

The Formation Wand uses a small amount of charge per block to place blocks chosen with the wand, which you have in your inventory, into the world in a line. Yes, it uses up the blocks from your inventory.

The Conversion Wand uses a small amount of charge per block to replace blocks of a certain type chosen with the wand with another type chosen with the wand, which you have in your inventory, into the world in a line. The blocks it 'mines' go into your inventory as a replacement. This lets you do things like sketch a construction in dirt and then replace the dirt with cobblestone later. Yes, it uses up blocks from your inventory.

In less detail; the Impulsion Wand uses moderate charge to act as a grappling hook, and the Illumination Wand uses large amounts of charge to make lights.

**Comment by Iceciro** [comment]
I would not be intending these wands to be part of Wizardry thing, just a general award for the purposes of making large scale building slightly easier for everyone.

**Comment by nivthefox** [comment]
Ironically, if it was just for wizardry I'd be slightly **less** concerned about what Chris has to say.  I think it's a valid concern for a player whose mod gives them this as a special thing to not want to add a shortcut to it that requires no investment.  I'll think about this some, but I do wonder whether it would be possible for an Astral Sorcerer to craft the Formation and Conversion wands for you, @Iceciro, and have the same effect.

**Comment by InterwovenWasTaken** [comment]
The Formation, Conversion, Impulsion, and Illumination Wands don't care who is holding them; the charge system fills itself from the environment. The main reason I *haven't* just handed over a couple of wands to Ice is that they're part of the general 'not supposed to be handed out' items - they're held items that cast active effects.

**Comment by InterwovenWasTaken** [comment]
I recently found out that the wand to move pre-existing blocks causes enormous problems with Astral Sorcery - apparently scaling anywhere from 'starlight network doesn't work right' to 'server crashes when the relevant chunk loads'.

Since I can hand out AS wands (and our new Astrologer can too once they have some!) should this be closed?
