### ISSUE TITLE
Add additional morphs for Druids

### ISSUE THREAD

**Issue by nivthefox** [SoSly/minecraft#28]
Please add recipe ideas as a comment to this issue.

**Comment by InterwovenWasTaken** [comment]
Well, I'm not a Druid, but some ideas of possible merit. Our druids may not care about some of these, especially the elementals? If no druid comments on these, probably just ignore them and close the issue. *Shrug*

Semi-Magical Animals
1) Hippocampus. Recipe would require a potion of water breathing, a potion of speed, and one Shiny Scales. Possibly also one sponge or prismarine crystals.

Advantages: Fast swimming, water breathing, night vision (for vision underwater)
Disadvantages: None or slow out of water.

Recipe explanation: A potion of water breathing and a potion of speed represent the abilities of the form, and a shiny scale represents the essence of the form, since it is a hippocampus drop. Sponges are the food used to tame hippocampi, and prismarine crystals are used to breed them - however, sponges may be too difficult to get.
(Sirens also drop shiny scales, so it isn't necessary to kill a peaceful Hippocampus to get the form if you fight a hostile siren.)

2) Hippogryph. Recipe would require a Gaia Spirit, a feather, gold hippogryph armor, and a rabbit's foot. Possibly use a hippogryph feather instead of a normal feather.

Advantages: Flight
Disadvantages: Somewhat large

Recipe explanation: The Gaia Spirit is for flight, tiering, and Botania involvement. The feather and the gold hippogryph armor are for the essence of the form. And the rabbit's foot is for the way to tame a hippogryph. A hippogryph feather would be more accurate, but also require killing a hippogryph. Like the elemental forms, below, this would be a more difficult to acquire defensive upgrade over the current bird forms.

3) Foxhound. Recipe would require leather, blaze powder, magma cream, and Netherrack.

Advantages: Fire immunity, night vision.
Disadvantages: Slightly reduced maximum hp.

Recipe explanation: Leather and blaze powder are their drops; magma cream is the potion ingredient for Fire Resistance, Netherrack is to actually require visiting the nether (or getting it from someone who has) since all the other materials are available in the Overworld.

Elementals
1) Blazes, Ice Wraiths, and Lightning Wraiths. Recipe would require Gaia Spirits, a blaze rod/dragon ice spikes/charged emerald, and a Molten Dawnstone Bucket.

Advantages: Flight, fire immunity for Blazes, knockback for the other two?
Disadvantages: None?

Recipe explanation: Gaia Spirits is for flight, tiering, Botania involvement, and 'elemental power'. Blaze rod/dragon ice spikes/charged emerald is for 'elemental essence' and moderate personal difficulty (as they require dungeon or dragon involvement,) and a Molten Dawnstone Bucket provides 'physical shape' and Embers involvement. The required Botania involvement is higher than the required Embers involvement because... they're still druids.

Possible issue: Elementals are stylish in a very different way to birds, and other than the hitbox, like hippogryphs, these would be a defensive upgrade over current bird forms.
