### ISSUE TITLE
Reconsider Vicio's power level

### ISSUE THREAD

**Issue by nivthefox** [SoSly/minecraft#30]
Vicio (the Astral Sorcery ritual) currently gives a 24 square radius of creative flight, +16 squares per lens (up to 5), times 4 with the Gelu ritual ... for no ongoing cost, once it's setup.  This concerns me greatly, as it gives full creative flight to everything near Fox Lake. I would like to limit this a bit, as this is well beyond the range I had expected to be possible when I first configured the server. 

My preferred solution is to do something that brings the maximum radius down to the 100-150 range ... which is about as much space as someone might conceivably claim as "their base" which makes it wonderful for inviting visitors over and marveling in the freedom of flight near your space without negating the work everyone else has put in for their own flight or double jump options.

I have thought of a few equations for how I'd suggest doing this:

(1) 16 base + 8/lens = 224
(2) 32 base + 0/lens = 128
(3) 24 base + 3/lens = 156
(4) 16 base + 5/lens = 164

I'm open to other ways of doing it, but the current live behavior is well outside the scope of what I realised could be done with Astral Sorcery.  This is the first time I've gone "that is way too much" with that mod.

**Comment by Affirmatron** [comment]
I am of the opinion that, generally speaking, flight is not that big of a deal given the sort of server we're playing on; but with that said:

That there are no ongoing costs is pretty wild. I can get up to some bonkers stuff with Blood Magic but I can't make everyone for a half-kilometre in every direction fly for what is essentially Minecraft-free.

I think option 2 is best, since it's the right size in my head and lowers the material cost to reduce the sting of the loss of strength and is divisible by 16.

I have no skin in the game, though, so perhaps my opinion isn't really important.

**Comment by Iceciro** [comment]
I'm bad at hiding my opinions on things, but yeah, the lack of ongoing costs, is pretty crazy. I'm also partial to Option 2, it's a neater number that doesn't require the lenses to be built.

**Comment by InterwovenWasTaken** [comment]
I am checking this for ongoing costs, because it's certainly *supposed* to have some. More news as I finish my magic science.

I hate the idea of a ritual that doesn't require the lenses; that's one of their primary functions, and the method by which overcharging a ritual (increasing its power but also increasing the damage and maintenance/upkeep needs) occurs.

Again, more news as I investigate.

**Comment by InterwovenWasTaken** [comment]
1) The ritual can run without a collector crystal structure while the appropriate constellation, Vicio, is in the sky at night.
2) The ritual can run without a collector crystal during the day, unexpectedly. That shouldn't happen, and I'm not sure why it does now when it didn't before - possibly it is a bug with Gelu, or more likely it is a 'Vicio day' and there are also 'non-Vicio days', or also more likely I was wrong before or I moved the structure into a better spot for starlight by accident at some point.
3) The ritual needs a collector crystal link to establish Crystal Lens links, but not to maintain them if it has all five.
4) The crystal has show no fracturing after at least three hours of testing, so unless I overcharge it, it looks like it doesn't fracture at any meaningful rate, and therefore will not need any meaningful maintenance at a 5-lens + Gelu radius.

With this data in mind, it seems reasonable to me to make it weaker. Especially because of point 2 - Gelu is supposed to increase power draw in order to power its range increase, but if passive power is enough then it changes to a benefit without drawbacks, which is inappropriate.

It is important to me 1) Aesthetically and 2) For the temptations of power that the Crystal Lenses provide a benefit, and ideally the bulk of the benefit - because they are also how you overcharge a crystal, causing Fracturing.

Therefore, 16 base + 8/lens is my favorite of the four options you offered. In my own calculations, I actually came up with 10 base + 8/lens as an option.
Lenses are available in the same tier of research as rituals; arguably they are a little easier to make, in fact.

Also, I was under the impression that Gelu was a 2.4x radius and 0.25x power effect. Can we change the stats of the Gelu trait itself?

**Comment by anomalagous** [comment]
I am also kind of in the boat where I don't feel like flight specifically around spawn/where we want to build is really that OP, but I have not really been concerned with the balance of things at all during this setup, so take that for what it's worth. I wouldn't be opposed to shrinking it down a little bit, although I really have no sense of what numbers would be best. Most of my inclination to nerf it comes from the notion that automatically flying around spawn when you double-jump takes away some of the fun of others who would rather not fly but actively use double-jump mechanics. As always, my biggest concern is that everyone is at maximum possible enjoyment and contentment, given the constraints inherent in a community server.

**Comment by nivthefox** [comment]
After some thought, we are going to limit this to 6 for the base ritual, +2/lens.  With Gelu's *4 that comes to 64 blocks, or 4 chunks exactly in radius.  This results in the following radius (though this is square, not circular like it will be in game)


![](https://cdn.discordapp.com/attachments/694250197445771375/703720844983009321/unknown.png)

While this is a very heavy nerf, it also results in the ritual no longer disrupting other players' ability to enjoy their play.  Specifically, it allows the Astral Sorcerer's base to be fully covered and a joy to visit, without impinging on others.

If other Astral Sorcerers want to add this to their own bases, flight can be extended by having multiple active rituals, one per "base", as it were.
